export const studentSchemas = {
  Student: {
    type: 'object' as const,
    properties: {
      id: { type: 'string' as const, example: 'clx1234567890' },
      fullName: { type: 'string' as const, example: 'Maria Fernanda Lopez Garcia' },
      documentType: { type: 'string' as const, example: 'CC' },
      documentNumber: { type: 'string' as const, example: '1098765432' },
      email: { type: 'string' as const, nullable: true, example: 'maria.lopez@email.com' },
      phone: { type: 'string' as const, example: '3001234567' },
      address: { type: 'string' as const, nullable: true, example: 'Calle 45 # 12-34, Bucaramanga' },
      guardianName: { type: 'string' as const, nullable: true, example: 'Pedro Lopez' },
      guardianPhone: { type: 'string' as const, nullable: true, example: '3109876543' },
      guardianEmail: { type: 'string' as const, nullable: true },
      enrollmentDate: { type: 'string' as const, format: 'date-time' as const, example: '2026-01-15T00:00:00.000Z' },
      initialPayment: { type: 'number' as const, example: 60000, description: 'Pago inicial de matricula en pesos' },
      totalProgramValue: { type: 'number' as const, example: 3500000, description: 'Valor total del programa en pesos' },
      status: { $ref: '#/components/schemas/StudentStatus' },
      paymentFrequency: { $ref: '#/components/schemas/PaymentFrequency' },
      firstCommitmentDate: { type: 'string' as const, format: 'date-time' as const, nullable: true },
      currentModule: { type: 'integer' as const, example: 2 },
      matriculaPaid: { type: 'boolean' as const, example: true },
      programId: { type: 'string' as const },
      advisorId: { type: 'string' as const },
      createdAt: { type: 'string' as const, format: 'date-time' as const },
      updatedAt: { type: 'string' as const, format: 'date-time' as const },
      program: {
        type: 'object' as const,
        properties: {
          id: { type: 'string' as const },
          name: { type: 'string' as const, example: 'Tecnico en Desarrollo de Software' },
        },
      },
      advisor: {
        type: 'object' as const,
        properties: {
          id: { type: 'string' as const },
          name: { type: 'string' as const, example: 'Juan Carlos Rodriguez' },
        },
      },
      totalPaid: { type: 'number' as const, example: 540000, description: 'Total pagado hasta la fecha' },
      remainingBalance: { type: 'number' as const, example: 2960000, description: 'Saldo pendiente' },
    },
  },
  CreateStudentInput: {
    type: 'object' as const,
    required: ['fullName', 'documentNumber', 'phone', 'enrollmentDate', 'initialPayment', 'totalProgramValue', 'programId', 'advisorId', 'paymentFrequency', 'firstCommitmentDate', 'paymentMethod'],
    properties: {
      fullName: { type: 'string' as const, minLength: 3, example: 'Maria Fernanda Lopez Garcia' },
      documentType: { type: 'string' as const, default: 'CC', example: 'CC' },
      documentNumber: { type: 'string' as const, minLength: 5, example: '1098765432' },
      email: { type: 'string' as const, format: 'email' as const, example: 'maria.lopez@email.com' },
      phone: { type: 'string' as const, minLength: 7, example: '3001234567' },
      address: { type: 'string' as const, example: 'Calle 45 # 12-34, Bucaramanga' },
      guardianName: { type: 'string' as const, example: 'Pedro Lopez' },
      guardianPhone: { type: 'string' as const, example: '3109876543' },
      guardianEmail: { type: 'string' as const, format: 'email' as const },
      enrollmentDate: { type: 'string' as const, format: 'date' as const, example: '2026-01-15' },
      initialPayment: { type: 'number' as const, minimum: 0, example: 60000 },
      totalProgramValue: { type: 'number' as const, minimum: 0, example: 3500000 },
      status: { $ref: '#/components/schemas/StudentStatus' },
      programId: { type: 'string' as const, example: 'clx_program_001' },
      advisorId: { type: 'string' as const, example: 'clx_user_001' },
      paymentFrequency: { $ref: '#/components/schemas/PaymentFrequency' },
      firstCommitmentDate: { type: 'string' as const, format: 'date' as const, example: '2026-02-15' },
      paymentMethod: { $ref: '#/components/schemas/PaymentMethod' },
      paymentReference: { type: 'string' as const, example: 'REF-12345' },
    },
  },
  UpdateStudentInput: {
    type: 'object' as const,
    properties: {
      fullName: { type: 'string' as const, minLength: 3 },
      documentType: { type: 'string' as const },
      email: { type: 'string' as const, format: 'email' as const },
      phone: { type: 'string' as const, minLength: 7 },
      address: { type: 'string' as const },
      guardianName: { type: 'string' as const },
      guardianPhone: { type: 'string' as const },
      guardianEmail: { type: 'string' as const, format: 'email' as const },
      status: { $ref: '#/components/schemas/StudentStatus' },
      programId: { type: 'string' as const },
      advisorId: { type: 'string' as const },
      enrollmentDate: { type: 'string' as const, format: 'date' as const },
      initialPayment: { type: 'number' as const, minimum: 0 },
      totalProgramValue: { type: 'number' as const, minimum: 0 },
      paymentFrequency: { $ref: '#/components/schemas/PaymentFrequency' },
      firstCommitmentDate: { type: 'string' as const, format: 'date' as const },
    },
  },
  StudentPaymentInfo: {
    type: 'object' as const,
    description: 'Resumen de informacion de pagos del estudiante',
    properties: {
      student: { $ref: '#/components/schemas/Student' },
      moduleValue: { type: 'number' as const, example: 573333, description: 'Valor calculado por modulo' },
      minimumPayment: { type: 'number' as const, example: 573333 },
      remainingBalance: { type: 'number' as const, example: 2960000 },
      commitments: {
        type: 'array' as const,
        items: { $ref: '#/components/schemas/PaymentCommitment' },
      },
    },
  },
};
