export const tenantSchemas = {
  Tenant: {
    type: 'object' as const,
    properties: {
      id: { type: 'string' as const, example: 'clx1234567890' },
      name: { type: 'string' as const, example: 'Instituto Educativo Elite' },
      slug: { type: 'string' as const, example: 'instituto-educativo-elite' },
      domain: { type: 'string' as const, nullable: true, example: 'elite.kaledsoft.tech' },
      email: { type: 'string' as const, nullable: true, example: 'admin@instituto-elite.com' },
      plan: { type: 'string' as const, example: 'BASICO' },
      status: { $ref: '#/components/schemas/TenantStatus' },
      subscriptionEndsAt: { type: 'string' as const, format: 'date-time' as const, nullable: true, example: '2026-12-31T23:59:59.000Z' },
      createdAt: { type: 'string' as const, format: 'date-time' as const },
      updatedAt: { type: 'string' as const, format: 'date-time' as const },
      _count: {
        type: 'object' as const,
        properties: {
          users: { type: 'integer' as const, example: 5 },
          students: { type: 'integer' as const, example: 120 },
          payments: { type: 'integer' as const, example: 450 },
        },
      },
    },
  },
  CreateTenantInput: {
    type: 'object' as const,
    required: ['name', 'slug', 'email'],
    properties: {
      name: { type: 'string' as const, example: 'Academia del Saber' },
      slug: { type: 'string' as const, example: 'academia-del-saber', description: 'Identificador unico URL-friendly (solo alfanumerico y guiones)' },
      email: { type: 'string' as const, format: 'email' as const, example: 'admin@academia-saber.com' },
      plan: { type: 'string' as const, example: 'BASICO', description: 'Plan de suscripcion' },
      subscriptionEndsAt: { type: 'string' as const, format: 'date-time' as const, nullable: true },
    },
  },
  UpdateTenantInput: {
    type: 'object' as const,
    properties: {
      name: { type: 'string' as const },
      slug: { type: 'string' as const },
      domain: { type: 'string' as const, nullable: true },
      status: { $ref: '#/components/schemas/TenantStatus' },
      plan: { type: 'string' as const },
      email: { type: 'string' as const, format: 'email' as const },
      subscriptionEndsAt: { type: 'string' as const, format: 'date-time' as const, nullable: true },
    },
  },
  TenantStats: {
    type: 'object' as const,
    properties: {
      total: { type: 'integer' as const, example: 25 },
      activos: { type: 'integer' as const, example: 18 },
      pendientes: { type: 'integer' as const, example: 3 },
      suspendidos: { type: 'integer' as const, example: 2 },
      cancelados: { type: 'integer' as const, example: 2 },
    },
  },
  TenantBranding: {
    type: 'object' as const,
    properties: {
      id: { type: 'string' as const },
      tenantId: { type: 'string' as const },
      logoUrl: { type: 'string' as const, nullable: true, example: 'https://storage.example.com/logo.png' },
      faviconUrl: { type: 'string' as const, nullable: true },
      primaryColor: { type: 'string' as const, example: '#1e3a5f' },
      secondaryColor: { type: 'string' as const, example: '#3b82f6' },
      accentColor: { type: 'string' as const, example: '#10b981' },
      fontFamily: { type: 'string' as const, example: 'Inter' },
      loginBgImage: { type: 'string' as const, nullable: true },
      loginBgGradient: { type: 'string' as const, nullable: true },
      footerText: { type: 'string' as const, nullable: true },
      customCss: { type: 'string' as const, nullable: true },
      darkMode: { type: 'boolean' as const, example: false },
    },
  },
  UpdateBrandingInput: {
    type: 'object' as const,
    properties: {
      logoUrl: { type: 'string' as const, format: 'uri' as const },
      faviconUrl: { type: 'string' as const, format: 'uri' as const },
      primaryColor: { type: 'string' as const, pattern: '^#[0-9a-fA-F]{6}$', example: '#1e3a5f' },
      secondaryColor: { type: 'string' as const, pattern: '^#[0-9a-fA-F]{6}$', example: '#3b82f6' },
      accentColor: { type: 'string' as const, pattern: '^#[0-9a-fA-F]{6}$', example: '#10b981' },
      fontFamily: { type: 'string' as const, example: 'Inter' },
      loginBgImage: { type: 'string' as const, format: 'uri' as const },
      loginBgGradient: { type: 'string' as const },
      footerText: { type: 'string' as const, maxLength: 500 },
      customCss: { type: 'string' as const },
      darkMode: { type: 'boolean' as const },
    },
  },
};
